# Use root/example as user/password credentials
version: '3.1'

services:
  avideo_encoder:
    image: localhost:5000/avideo_encoder
    restart: always
    links:
      - db
    ports:
      - 8082:8000

  avideo:
    image: localhost:5000/avideo_platform
    restart: always
    links:
      - db
    ports:
      - 8081:8000

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hello123!
    ports:
      - 3306:33060

  adminer:
    image: adminer
    restart: always
    ports:
      - 9001:8080

