version: '3'

services:
  proxy:
    image: nginx_aprende
    restart: always
    environment:
      CERTBOT_EMAIL: "ssl@aprendecr.com"
    #ports:
    #  - "80:80"
    #  - "443:443"
    network_mode: host
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro


